# Generated by Django 5.2.7 on 2025-12-12 10:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        help_text="Например: 1, 5, 12А, 7Т",
                        max_length=10,
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(1)],
                        verbose_name="Номер маршрута",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Например: Центр - Восток",
                        max_length=200,
                        verbose_name="Название маршрута",
                    ),
                ),
                (
                    "bus_type",
                    models.CharField(
                        choices=[
                            ("bus", "Автобус"),
                            ("trolleybus", "Троллейбус"),
                            ("electric_bus", "Электробус"),
                            ("minibus", "Маршрутка"),
                        ],
                        max_length=20,
                        verbose_name="Тип транспорта",
                    ),
                ),
                (
                    "start_point",
                    models.CharField(
                        help_text="Название начальной остановки",
                        max_length=200,
                        verbose_name="Начальная точка",
                    ),
                ),
                (
                    "end_point",
                    models.CharField(
                        help_text="Название конечной остановки",
                        max_length=200,
                        verbose_name="Конечная точка",
                    ),
                ),
                (
                    "start_coordinates",
                    models.JSONField(
                        help_text='Формат: {"lat": 42.8746, "lng": 74.5698}',
                        verbose_name="Координаты начальной точки",
                    ),
                ),
                (
                    "end_coordinates",
                    models.JSONField(
                        help_text='Формат: {"lat": 42.8900, "lng": 74.6100}',
                        verbose_name="Координаты конечной точки",
                    ),
                ),
                (
                    "path",
                    models.JSONField(
                        help_text='Массив координат: [{"lat": 42.8746, "lng": 74.5698}, ...]',
                        verbose_name="Путь маршрута",
                    ),
                ),
                (
                    "working_hours",
                    models.CharField(
                        blank=True,
                        help_text="Например: 05:52 - 22:11",
                        max_length=50,
                        null=True,
                        verbose_name="Время работы",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Если False, маршрут не показывается пассажирам",
                        verbose_name="Активен",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Маршрут",
                "verbose_name_plural": "Маршруты",
                "ordering": ["number"],
                "indexes": [
                    models.Index(
                        fields=["number"], name="route_route_number_ce1403_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="route_route_is_acti_3ede5a_idx"
                    ),
                ],
            },
        ),
    ]
