# Generated by Django 5.2.7 on 2025-12-12 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bus", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Заполняется автоматически при создании",
                        verbose_name="Время начала смены",
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="Заполняется когда водитель завершает смену",
                        null=True,
                        verbose_name="Время окончания смены",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Активна"), ("completed", "Завершена")],
                        default="active",
                        max_length=20,
                        verbose_name="Статус смены",
                    ),
                ),
                (
                    "bus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shifts",
                        to="bus.bus",
                        verbose_name="Автобус",
                    ),
                ),
            ],
            options={
                "verbose_name": "Смена",
                "verbose_name_plural": "Смены",
                "ordering": ["-start_time"],
            },
        ),
    ]
