# Generated by Django 5.2.7 on 2025-12-12 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("shift", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="shift",
            name="driver",
            field=models.ForeignKey(
                limit_choices_to={"role": "driver"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shifts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Водитель",
            ),
        ),
        migrations.AddIndex(
            model_name="shift",
            index=models.Index(
                fields=["driver", "status"], name="shift_shift_driver__3667a7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shift",
            index=models.Index(
                fields=["bus", "status"], name="shift_shift_bus_id_f62391_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shift",
            index=models.Index(
                fields=["status", "-start_time"], name="shift_shift_status_0cacd3_idx"
            ),
        ),
    ]
