# Generated by Django 5.2.7 on 2025-12-12 12:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bus", "0002_initial"),
        ("shift", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="shift",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("bus",),
                name="unique_active_shift_per_bus",
                violation_error_message="На этом автобусе уже есть активная смена",
            ),
        ),
        migrations.AddConstraint(
            model_name="shift",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("driver",),
                name="unique_active_shift_per_driver",
                violation_error_message="У водителя уже есть активная смена",
            ),
        ),
    ]
