# Generated by Django 5.2.7 on 2025-12-12 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bus", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Диапазон: -90 до +90",
                        max_digits=9,
                        verbose_name="Широта",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Диапазон: -180 до +180",
                        max_digits=9,
                        verbose_name="Долгота",
                    ),
                ),
                (
                    "speed",
                    models.FloatField(
                        blank=True,
                        help_text="Скорость в км/ч",
                        null=True,
                        verbose_name="Скорость",
                    ),
                ),
                (
                    "heading",
                    models.FloatField(
                        blank=True,
                        help_text="Градусы: 0-360 (0=север, 90=восток)",
                        null=True,
                        verbose_name="Направление",
                    ),
                ),
                (
                    "accuracy",
                    models.FloatField(
                        blank=True,
                        help_text="Точность в метрах",
                        null=True,
                        verbose_name="Точность GPS",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время получения координаты"
                    ),
                ),
                (
                    "bus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="bus.bus",
                        verbose_name="Автобус",
                    ),
                ),
            ],
            options={
                "verbose_name": "Местоположение автобуса",
                "verbose_name_plural": "Местоположения автобусов",
                "ordering": ["-timestamp"],
            },
        ),
    ]
