# Generated by Django 5.2.7 on 2025-12-12 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("busLocation", "0001_initial"),
        ("shift", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="buslocation",
            name="shift",
            field=models.ForeignKey(
                help_text="Координаты привязаны к смене",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="locations",
                to="shift.shift",
                verbose_name="Смена",
            ),
        ),
        migrations.AddIndex(
            model_name="buslocation",
            index=models.Index(
                fields=["bus", "-timestamp"], name="busLocation_bus_id_d94810_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="buslocation",
            index=models.Index(
                fields=["shift", "-timestamp"], name="busLocation_shift_i_d6093d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="buslocation",
            index=models.Index(
                fields=["-timestamp"], name="busLocation_timesta_1b90a8_idx"
            ),
        ),
    ]
