# Generated by Django 5.2.7 on 2025-12-12 10:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(
                        help_text="Например: 01ABC123, KG 123 BCD",
                        max_length=20,
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(3)],
                        verbose_name="Гос. номер",
                    ),
                ),
                (
                    "bus_type",
                    models.CharField(
                        choices=[
                            ("bus", "Автобус"),
                            ("trolleybus", "Троллейбус"),
                            ("electric_bus", "Электробус"),
                            ("minibus", "Маршрутка"),
                        ],
                        max_length=20,
                        verbose_name="Тип транспорта",
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True,
                        help_text="Например: Mercedes-Benz Sprinter, ПАЗ-32054",
                        max_length=100,
                        null=True,
                        verbose_name="Модель",
                    ),
                ),
                (
                    "capacity",
                    models.IntegerField(
                        blank=True,
                        help_text="Количество пассажиров",
                        null=True,
                        verbose_name="Вместимость",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Если False, автобус на ремонте или списан",
                        verbose_name="Активен",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Автобус",
                "verbose_name_plural": "Автобусы",
                "ordering": ["registration_number"],
            },
        ),
    ]
