# Generated by Django 5.2.7 on 2025-12-12 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bus", "0001_initial"),
        ("route", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="bus",
            name="assigned_driver",
            field=models.ForeignKey(
                blank=True,
                help_text="Водитель, закреплённый за этим автобусом",
                limit_choices_to={"role": "driver"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_buses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Назначенный водитель",
            ),
        ),
        migrations.AddField(
            model_name="bus",
            name="route",
            field=models.ForeignKey(
                blank=True,
                help_text="Маршрут, на котором работает автобус",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="buses",
                to="route.route",
                verbose_name="Маршрут",
            ),
        ),
        migrations.AddIndex(
            model_name="bus",
            index=models.Index(
                fields=["registration_number"], name="bus_bus_registr_a20520_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bus",
            index=models.Index(fields=["is_active"], name="bus_bus_is_acti_d7321e_idx"),
        ),
    ]
